import Link from "next/link";
import { ControlFrame } from "@/components/admin/control-frame";
const steps = [
 { title: "1. Çalışma alanını ve bekleyen işi bul", screen: "Genel Bakış", route: "", look: "FineDine çalışma alanını seç. Eksik mercekli brief sayısı son 14 günün başarılı brief’lerinden gelir. Taban ve aday oranları referans vakaların kaçının kuralları geçtiğini söyler. Düşen işler ayrı sayılır.", press: "İnceleme kartını aç.", happens: "Burger House için en yeni başarılı brief, işletme adıyla kuyrukta görünür. Başarısız worker bu kuyruğa girmez; Vaka izi ve Genel Bakış üzerinden takip edilir.", stays: "Bu sayfayı açmak model çalıştırmaz ve lead’i değiştirmez." },
 { title: "2. Üç merceğin okuyacağı ortak kartı tanı", screen: "İnceleme", route: "/reviews", look: "Burger House satırını aç. Örnekte ICP uyumu 87; modül sırası Sipariş ve ödeme, QR menü, CRM ve sadakat. İlk modül birincildir. Açı, konuşma, paket, hariç tutulanlar, iddialar, kanıt, brief bitiş zamanı ve aynı hesaptaki lokasyon sayısını oku. Bunlar örnek değerlerdir; kendi kartındaki kayıt esastır.", press: "Burger House işletme satırını aç.", happens: "Teknik, Alan ve Satış aynı koşunun aynı kartını görür. Head agent yoksa kart bunu açıkça söyler; brief yine incelenebilir.", stays: "Kartı okumak saklanan AI cevabını değiştirmez. Lokasyon sayısı konuşmadan tahmin edilmez; aynı hesaptaki lead’ler sayılır." },
 { title: "3. Teknik merceği kaynak ve iş akışını değerlendirir", screen: "Vaka izi → İnceleme", route: "/trace", look: "Burger House’u aç. Ortak kartın kaynak zamanını ve iddia cümlesini karşılaştır. Kaynak zamanı brief’in bitişidir, yorumun gerçek yılı değildir. Altında Site, Yorum, ICP, Karar ve CRM satırlarının süre, USD ve hatalarını incele.", press: "İnceleme’ye dön; Teknik merceğinde Kaldı, Eski kaynak, Bugün bakar ve bir cümle not seçip Kararı kaydet’e bas.", happens: "Teknik hükmü eklenir. Alan ve Satış eksik olduğu için Burger House kuyrukta kalır. Sınıf, şiddet ve açıklama Kaldı için zorunludur.", stays: "Hüküm hiçbir zaman AI cevabını silmez veya düzeltmez. Başarısız worker kayıtları Vaka izi’nde kalır." },
 { title: "4. Alan merceği modül sırasını ve paketi değerlendirir", screen: "İnceleme", route: "/reviews", look: "Alan merceği aynı kartın birincil modülüne, sıralı modüllerine, hariç tutulanlara ve paketine bakar. Burger House zaten sipariş sistemi kullanıyorsa Sipariş ve ödeme’nin ilk sırada olması yanlış olabilir.", press: "Kaldı → Paket uyumsuzluğu → Bugün bakar seç; nedenini bir cümle yaz ve Kararı kaydet’e bas.", happens: "Alan hükmü Teknik hükmünün yanına eklenir. Satış henüz bakmadığı için satır durur. Her kişi yalnızca kendisine atanmış merceğin formunu doldurabilir.", stays: "Teknik hükmü üzerine yazılmaz. AI modül sırası otomatik değiştirilmez; bu değerlendirme yalnızca insan hükmüdür." },
 { title: "5. Satış merceği SDR’ın kullanacağı cümleyi değerlendirir", screen: "İnceleme", route: "/reviews", look: "Satış merceği aynı kartın konuşma, lokasyon, paket ve iddia satırlarını okur. Konuşma 20 lokasyon diyorsa karttaki gerçek hesap sayısıyla karşılaştırır. Zaten müşteri veya hedef profil dışı olması Kimlik uyuşmazlığı; dayanaksız gelir vaadi Dayanaksız iddia olabilir.", press: "Geçti, Kaldı veya Tekrar bak seçip kendi notunla Kararı kaydet’e bas.", happens: "Üç merceğin güncel hükmü tamamlanır. Üçü de Kaldı diyebilir; hemfikir olmaları şart değildir. Burger House inceleme kuyruğundan çıkar ve Referans vakalar üzerinden açılabilir.", stays: "Geçti sınıf ve şiddeti temizler. Yeni hüküm eski kayıtları silmez. Merceksiz eski kayıtlar üçlü kapıya sayılmaz." },
 { title: "6. Beklenen davranışı insan kurallarına çevir", screen: "Referans vakalar → incelemeyi aç", route: "/golden", look: "Burger House incelemesini aç. Eksik mercek varsa adları görünür ve Referans vaka yap kapalı kalır. Üçü tamamlandıysa beklenen davranışı yaz: örneğin puan 70–100, izinli birincil modül CRM ve sadakat, yasak iddia guaranteed revenue increase, yasak açı online ordering replacement.", press: "Referans vaka yap’a bas ve beklenen kuralları doldur. İzinli modülleri etiketlerinden seç.", happens: "Form, kuralları AI cevabından kopyalamaz. Yalnızca ilk modül izinli kümede olmalıdır; Sipariş ve ödeme üçüncü sıradaysa tek başına Modül hatası değildir.", stays: "Kuralları yazmak brief’i yeniden üretmez. Henüz referans vaka kaydedilmez; canlı ICP, paket ve oyun kitabı değişmez." },
 { title: "7. Önizlemeyi oku ve referans vakayı dondur", screen: "İnceleme · referans vaka formu", route: "/reviews", look: "Formdaki Bu kurallarla donmuş çıktı geçer cümlesini veya kalış nedenlerini oku. Örnekte birincil Sipariş ve ödeme, izinli birincil CRM ve sadakat ise Modül nedeniyle kalır. Yasak metinler büyük-küçük harf duyarsız alt dizgi olarak aranır.", press: "Referans vakayı kaydet’e bas.", happens: "Sunucu işletme adı, adres, rating, yorum sayısı, fiyat, lokasyon, site audit’i, yorum analizini, brief bağlamını, hariç modülleri ve kanıtları bu çalışma alanından dondurur. Saklanan çıktı kaynak koşudan, beklenen kurallar insandan gelir. En sıkı güncel Kaldı şiddeti seçilir; hepsi Geçti ise Kayıt olur.", stays: "Önizleme model çağırmaz. Referans vaka SemanticMemory’ye yazılmaz. Lead daha sonra değişse de bu girdi ve çıktı snapshot’ları değişmez." },
 { title: "8. O günün cevabını taban olarak say", screen: "Referans vakalar", route: "/golden", look: "Kaydedilmiş Burger House vakasını ve beklenen kurallarını esas al. Taban, o gün saklanan cevabın bu kurallara uyup uymadığını ölçer.", press: "İnceleyen olarak Saklanan çıktıları taban olarak say’a bas.", happens: "Her vakanın donmuş çıktısı puan bandı, birincil modül, yasak iddia ve yasak açı kurallarıyla sayılır. Geçen/toplam oranı Genel Bakış’ta son taban olarak görünür.", stays: "Claude veya Gemini çağrılmaz. Yeni karar üretilmez. Lead ve kaynak brief yerinde kalır." },
 { title: "9. Bugünkü head agent ile aday kararları üret", screen: "Karşılaştırma", route: "/golden/compare", look: "Yönetici vaka sayısını ve her vaka bugünkü head agent ile bir kez karar üretir, lead’e yazılmaz onayını okur. Aynı çalışma alanında sürmekte olan aday varsa ikinci aday başlatılamaz.", press: "Onay kutusunu işaretle ve Donmuş girdiden aday kararları üret’e bas. Sonra Koşu durumunu yenile ile tamamlanmasını izle.", happens: "API mevcut agent-runs kuyruğuna iş bırakır. Worker yalnızca donmuş girdiden, güncel head agent promptuyla yeni karar üretir ve aynı kurallarla sayar. Araç döngüsü, canlı crawl ve canlı yorum okuma kapalıdır. Head agent kapalı veya alan F&B değilse vaka Head agent kullanılamıyor nedeniyle kalır; koşu yine tamamlanır. Bir vaka hatası diğerlerini durdurmaz.", stays: "Adayın cevabı sadece değerlendirme sonucuna yazılır. Lead’e, müşterinin brief’ine veya kaynak AgentRun’a yazılmaz. Model kullanımı bu adımda oluşur." },
 { title: "10. Farkı oku ve kontrol sonucunu kabul et", screen: "Karşılaştırma → Denetim", route: "/golden/compare", look: "İki başarılı koşuyu seç: eski taban, yeni aday. N bozuldu, N düzeldi, N aynı sayımını oku. Tabanda geçen adayda kalırsa bozuldu; tersi düzeldi. Burger House satırında işletme adı, kalış nedeni ve iki karar kartını yan yana karşılaştır.", press: "Yönetici gerekçesini yazıp Kontrol sonucunu kabul et’e basabilir. Denetim’de işlemin gerekçesini oku.", happens: "Kabul, değerlendirme sonucuna ait bir denetim kaydı ekler. Sonuçları canlı ayara taşımak gerekirse mevcut kalibrasyon süreci ayrı yürür ve taslağı yazan kişi yayınlayamaz.", stays: "Accept does not publish live settings: Kabul canlı ayarları yayınlamaz. Canlı ICP, paket ve oyun kitabı değişmez. Hiçbir hüküm veya kabul AI cevabını silmez." },
];
export default async function GuidePage({ searchParams }: { searchParams: Promise<{ workspaceId?: string }> }) {
 const { workspaceId } = await searchParams;
 const suffix = workspaceId ? `?workspaceId=${encodeURIComponent(workspaceId)}` : "";
 return <ControlFrame workspaceId={workspaceId}><section className="space-y-5"><h1 className="text-2xl font-semibold">Nasıl çalışır</h1>
 <p className="text-sm text-[var(--revint-text-2)]">Burger House’un aynı brief’ini üç mercek okur. Teknik kaynak ve iş akışına, Alan modül sırası ve pakete, Satış konuşma ve iddialara bakar. Bunlar üç ayrı analiz değil, tek kart üzerinde üç ayrı insan hükmüdür.</p>
 <p className="text-sm text-[var(--revint-text-2)]">Yetki ile mercek ayrıdır: İzleyici okur, merceği atanmış İnceleyen hüküm ve referans vaka yazar, Yönetici aday koşuyu başlatır. Sana bir mercek atanmadı mesajı varsa bir yöneticinin hesabına mercek ataması gerekir. Şiddetler: Bugün bakar, Bu hafta, Kayıt.</p>
 {steps.map(step => <article key={step.title} className="space-y-3 rounded-xl border border-[var(--revint-border)] bg-[var(--revint-card)] p-5"><h2 className="text-lg font-semibold">{step.title}</h2><p className="text-sm">Ekran: <Link className="text-[var(--revint-500)]" href={`/admin/control${step.route}${suffix}`}>{step.screen}</Link></p><dl className="space-y-3 text-sm">{[["Neye bak",step.look],["Ne yap",step.press],["Ne olur",step.happens],["Ne değişmez",step.stays]].map(([label,value]) => <div key={label}><dt className="font-medium">{label}</dt><dd className="mt-1 text-[var(--revint-text-2)]">{value}</dd></div>)}</dl></article>)}
 </section></ControlFrame>;
}
